### ISSUE TITLE
Does it communicate between iOS and Android devices?

### ISSUE THREAD

**Issue by heygarvish** [alexcmgit/ttt#2]
It's not an issue but more of a question.

1. Does this app connect iOS and Android devices?
2. Did you use real devices or emulators at the time of testing and development?

Thanks for your answer and time 😊

**Comment by alexcmgit** [comment]
> Does this app connect iOS and Android devices?

Not tested on iOS. Although the core library behind this app seems to supported all major platforms (except Linux).

![image](https://user-images.githubusercontent.com/51419598/235734675-653aa2e5-e08f-409a-8edb-6895e2f141f0.png)

> Did you use real devices or emulators at the time of testing and development?

Real android devices, emulators are harsh to configure for wireless APIs.

---

> Thanks for your answer and time 😊

You're welcome, thanks for the interest, if you have any other questions let me know.
